== Aggregate
:guide-src: ../../../../../samples/memento-guide/src/test/groovy/memento/guide

An aggregate in Memento is a class extending `memento.Aggreggate`:

.Aggregate
```groovy
class MyAggregate extends Aggregate {
  String clientId
}
```

=== Creating

Before applying any event to the aggregate, we need to create an instance of it. The only attribute required up front
is the aggregate property `id`. All events applied to that aggregate will be related to it via the aggregate id.

For example, a possible way to do it is to create a `static method`:

.Create Aggregate (static)
```groovy
include::{guide-src}/aggregate/AggregateSpec.groovy[tag=creating_static_method, indent=0]
```

or maybe using a constructor:

.Create Aggregate (Constructor)
```groovy
include::{guide-src}/aggregate/AggregateSpec.groovy[tag=creating_java_constructor, indent=0]
```

Of course we can short it with Groovy's `@InheritConstructors`:

.Create Aggregate (@InheritConstructors)
```groovy
include::{guide-src}/aggregate/AggregateSpec.groovy[tag=creating_groovy_constructor, indent=0]
```

=== Adding events

Once we've got an aggregate instance we can add events to it. An aggregate represents a domain context where a set of
events will be applied. For example, imagine an events over the aggregate `Delivery` such as:

- **REQUESTED**: a client has bought something and has triggered a new delivery
- **RECEIVED**: once the purchase arrives to the client's address the delivery received event is applied

The aggregate model could be modelled as:

.Adding events
```groovy
include::{guide-src}/aggregate/nobind/DeliveryProcess.groovy[indent=0]
```

And the events we'd like to use. Please **notice how the name of the events properties match the aggregate properties**,
that will be important later on:

.DeliveryRequested
```groovy
include::{guide-src}/aggregate/nobind/DeliveryRequested.groovy[]
```

.DeliveryReceived
```groovy
include::{guide-src}/aggregate/nobind/DeliveryReceived.groovy[]
```

Now lets see how do we apply these events to the aggregate:

.Aggregate#apply
```groovy
include::{guide-src}/aggregate/nobind/Delivery.groovy[]
```

<1> Triggers event versioning
<2> Changes aggregate state

The original `super.apply(event)`, only triggers event versioning. Event versioning means:

- **The applied event is given a version id** so that we know which order the events happened.
- **The applied event is given a unique id** to the event when applied to the aggregate.

Apart from these characteristics **we'd like to update the state of the aggregate**, that's why we create as many overloaded
apply methods as the number of events we'd like to apply to the aggregate. However is a little bit verbose and there
are a couple of methods specifically created to avoid creating this extra `apply` methods, the `bind(...)` methods
explained in the next section.

Once you've got your aggregate you can use it and add your events. This is a Spock test example:

.Adding events (no-bind)
```groovy
include::{guide-src}/aggregate/nobind/AggregateNoBindSpec.groovy[tag=adding_events]
```

=== Bind methods

These overloaded `apply` methods are pretty common that's why there's an alternative to avoid all that boilerplate code.
If we reviewed the previous example, but now using the `bind` method:

.Aggregate with bind methods
```groovy
include::{guide-src}/aggregate/full/Delivery.groovy[indent=0]
```

<1> The `Aggregate` class has a hook method `Aggregate#configure()` that should be used to register the functions telling the
aggregate how to process incoming events
<2> In order to avoid boilerplate code, the `Aggregate#bind(...)` methods. `Aggregate#bind(Class<Event)` copies the
properties matching the aggregate

Then event handing should work the same:

.Adding events (bind)
```groovy
include::{guide-src}/aggregate/full/AggregateFullSpec.groovy[tag=adding_events]
```

In this example both `Delivery` and `Requested` classes have a field named `clientId`. So by using:

.bind(Event)
```groovy
bind(Requested)
```

Every time the `Requested` event is applied to the `Delivery` instance it will copy the value from `Requested#clientId` to
`Delivery#clientId`.

There's a variant of this method that allows to handle an array of event types to be applied:

.bind(Event...)
```groovy
bind(Requested, Received...)
```

There's another method `Aggregate#bind(Event, Closure)` when the logic is more complex.

.bind(Event, Closure)
```groovy
bind(Requested) { Delivery delivery, Requested event ->
    delivery.clientId = event.clientId
}
```

The Closure params are the Aggregate type the event is going to be applied to, and the event type is going to be applied.
Imagine we've got events with properties not matching the aggregate properties:

.DeliveryRequested (custom)
```groovy
include::{guide-src}/aggregate/bindcustom/DeliveryRequested.groovy[]
```

.DeliveryReceived (custom)
```groovy
include::{guide-src}/aggregate/bindcustom/DeliveryReceived.groovy[]
```

Then you can match the state of the aggregate using the `bind(Class, Closure)` methods inside the `void configure()` method
block:

.Delivery (custom events)
```groovy
include::{guide-src}/aggregate/bindcustom/Delivery.groovy[]
```

There's still something to comment on the `bind(Class, Closure)` method usage...

[sidebar]
.Why Event<Aggregate> should match Aggregate ?
****

When using the `bind(EventType, Closure)` method, it's important to use the Aggregate in the generics argument of the
Event:

.Use aggregate in event generics
```groovy
// class EventType extends Event<AggregateType> {}
class Requested extends Event<Delivery> {}
class Received extends Event<Delivery> {}
class Loaded extends Event<Delivery> {}

// class AggregateType extends Aggregate {}
class Delivery extends Aggregate {}
```

If we forgot to add the generic argument, for example:

.Forgot aggregate in event generics
```groovy
// class EventType extends Event<AggregateType> {}
class Requested extends Event {}
class Received extends Event {}
class Loaded extends Event {}

// class AggregateType extends Aggregate {}
class Delivery extends Aggregate {}
```

When using the `bind(Class, Closure)` method the event type hint wouldn't be recognized, so instead of seeing this
in your IDE:

.bind
```groovy
bind(EventType) { AggregateType agg, EventType event ->
 // here the aggregate specific type is recognized
}
```

Your method would look more like the following:

.bind
```groovy
bind(EventType) { Aggregate agg, EventType event ->
 // here the aggregate specific type is not recognized
}
```

****

=== Design

So far you may have seen that an aggregate class could be design in different ways. We'd like to comment a little bit
on every different design strategy.

==== Method chaining

Method chaining strategy could be suited for:

- Situations you'd want every time an event is applied the updated aggregate is returned.
- Proofs of concepts where you'd like to see how all possible events are going to be rendered or store in the underlying event store
- Still your methods can apply validations before applying the events

Here we have an example with methods which always return the aggregate. See how by having these methods we can apply
validation. In this case we're using link:https://docs.groovy-lang.org/latest/html/documentation/#_groovy_contracts_design_by_contract_support_for_groovy[Groovy Contracts]
to make sure certain methods are not used without meeting certain conditions.

.Chained Aggregate
```groovy
include::{guide-src}/aggregate/design/chain/PatientCase.groovy[]
```

This design allows using the aggregate this way:

.Chained Aggregate usage
```groovy
include::{guide-src}/aggregate/design/chain/ChainDesignSpec.groovy[tag=chained, indent=0]
```

==== Void

Although method chaining is really appealing, but most of the time in real application we may face that our aggregate
is created and updated in different moments in time, so we may find no use on chaining the method calls, there are also
some motivations for using the void strategy:

- Your aggregate wants to stick to an interface and that interface doesn't know anything about the aggregate
- You don't want to return the aggregate every time an event is applied
- Still your aggregate methods can apply validations before applying the events

Following the same example, lets say that the medical procedure is already defined in an interface:

.Medical Procedure
```groovy
include::{guide-src}/aggregate/design/voidtype/MedicalProcedure.groovy[]
```

Then your aggregate may look like this:

.Aggregate (void)
```groovy
include::{guide-src}/aggregate/design/voidtype/PatientCase.groovy[]
```

And then imagine you are going to update the aggregate in different REST calls. For instance the case will be opened in
a post call and the subsequent put calls may reload it from the event store and update it:

.Void type usage
```groovy
include::{guide-src}/aggregate/design/voidtype/VoidDesignSpec.groovy[tag=usage, indent=0]
```

==== Raw apply

Nothing prevents you from using apply methods directly without creating any higher structure. Some scenarios for this
could be:

- You don't want to write any more code than you'd think is necessary to apply events
- Validations are done outside the aggregate

Of course up front the aggregate will be lighter:

.Raw aggregate
```groovy
include::{guide-src}/aggregate/design/raw/PatientCase.groovy[]
```

And then only using the default `Aggregate#apply(event)` method:

.Raw usage
```groovy
include::{guide-src}/aggregate/design/raw/RawDesignSpec.groovy[tag=usage, indent=0]
```