== Getting started
:guide-src: ../../../../../samples/memento-guide/src/test/groovy/memento/guide

The following example presents a **Document** aggregate:

- The Document can support different types of events such as **creating a document** (Created)
or **appending text** to the document (Appended).
- Also an **EventStore** implementation is created to store the aggregate events. This particular implementation stores events
and snapshots **as csv files**.

[source, groovy]
.save an aggregate
----
@Grab('com.github.grooviter:memento-csv:0.1.0')
include::{guide-src}/GettingStartedSpec.groovy[tag=getting_started_script,indent=0]
----

<1> The events used should extend the Event interface and have as generic value the class of the Aggregate
<2> Creating an aggregate. Check the link:#_aggregate[Aggregate section to know more]
<3> Configuring how the aggregate is going to apply the events. The `void configure() {}` method is a hook in the aggregate used to register how
events are going to be applied to the aggregate. There are some built-in `bind(...)`
functions to avoid creating boilerplate code. For example if `Created` has a `title` property, the `bind(class)` method
when applying the `Created` event to the `Document` aggregate, it will set the aggregate `title` property with
the `Created` event `title` property.
<4> Configuring Memento engine responsible for storing aggregate events and snapshots. Is always mandatory to configure
at least the **storage, serialization and event bus** you're going to use. By default we are using a csv file storage to
store both events and snapshots. Creating snapshots every two events. And the even bus we've configured is just
printing out the events inserted in the event store.
<5> Creating an aggregate and adding events to it
<6> Storing the aggregate state to the configured memento engine.

If you take a look at the **events.csv** file you will see the following.

[source, shell]
.events.csv
----
...-6740974752dc|1|Created|{"title":"Memento","aggregateId":"5f5469ba-a031-4ccb...
...-6740974752dc|2|Appended|{"content":"A man who, as a result of an injury","aggregate...
...
----