micronaut:
  application:
    name: mementoCargo

  server:
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**

datasources:
  default:
    url: jdbc:postgresql://db/cargo
    driverClassName: org.postgresql.Driver
    username: cargo
    password: cargo
    schema-generate: none
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true

memento:
  snapshot:
    threshold: 20