micronaut:
  application:
    name: mementoCargo

  server:
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
          paths: classpath:META-INF/swagger/views/swagger-ui
          mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:postgresql://localhost/cargo
    driverClassName: org.postgresql.Driver
    username: cargo
    password: cargo
    schema-generate: none
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true

memento:
  snapshot:
    threshold: 20